use student_info
-- Exercise 1: Create a View ---

CREATE VIEW EMPSALARY AS 
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY
FROM EMPLOYEES;

-- Retrive the Records --
SELECT * FROM EMPLOYEES;

-- Exercise 2: Update a View --

CREATE OR REPLACE VIEW EMPSALARY  AS 
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

-- Exercise 3: Drop a View --

DROP VIEW EMPSALARY;
